server:
  port: 8080
  servlet:
    context-path: /multimedia
spring:
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
props:
  fileDirPath: 'E:\question'